# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.setWindowModality(QtCore.Qt.ApplicationModal)
        Dialog.resize(548, 478)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.verticalLayout.setContentsMargins(100, -1, 100, -1)
        self.verticalLayout.setObjectName("verticalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout.addItem(spacerItem)
        self.userInput = QtWidgets.QLineEdit(Dialog)
        self.userInput.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.userInput.sizePolicy().hasHeightForWidth())
        self.userInput.setSizePolicy(sizePolicy)
        self.userInput.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.userInput.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.userInput.setText("")
        self.userInput.setAlignment(QtCore.Qt.AlignCenter)
        self.userInput.setDragEnabled(True)
        self.userInput.setObjectName("userInput")
        self.verticalLayout.addWidget(self.userInput)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout.addItem(spacerItem1)
        self.passInput = QtWidgets.QLineEdit(Dialog)
        self.passInput.setEnabled(True)
        self.passInput.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.passInput.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.passInput.setInputMask("")
        self.passInput.setText("")
        self.passInput.setAlignment(QtCore.Qt.AlignCenter)
        self.passInput.setDragEnabled(True)
        self.passInput.setObjectName("passInput")
        self.verticalLayout.addWidget(self.passInput)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout.addItem(spacerItem2)
        self.login = QtWidgets.QPushButton(Dialog)
        self.login.setObjectName("login")
        self.verticalLayout.addWidget(self.login)
        self.registrar = QtWidgets.QPushButton(Dialog)
        self.registrar.setObjectName("registrar")
        self.verticalLayout.addWidget(self.registrar)
        self.verticalLayout_2.addLayout(self.verticalLayout)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.userInput.setPlaceholderText(_translate("Dialog", "Usuario"))
        self.passInput.setPlaceholderText(_translate("Dialog", "Contraseña"))
        self.login.setText(_translate("Dialog", "Iniciar Sesión"))
        self.registrar.setText(_translate("Dialog", "Registro"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
