# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'menu.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Menu(object):
    def setupUi(self, Menu):
        Menu.setObjectName("Menu")
        Menu.resize(500, 625)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(Menu)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.welcomeLabel = QtWidgets.QLabel(Menu)
        self.welcomeLabel.setMaximumSize(QtCore.QSize(16777215, 40))
        self.welcomeLabel.setTextFormat(QtCore.Qt.MarkdownText)
        self.welcomeLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.welcomeLabel.setObjectName("welcomeLabel")
        self.verticalLayout.addWidget(self.welcomeLabel)
        spacerItem = QtWidgets.QSpacerItem(10, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        self.verticalLayout.addItem(spacerItem)
        self.recomendacionesButton = QtWidgets.QPushButton(Menu)
        self.recomendacionesButton.setObjectName("recomendacionesButton")
        self.verticalLayout.addWidget(self.recomendacionesButton)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout.addItem(spacerItem1)
        self.listadoButton = QtWidgets.QPushButton(Menu)
        self.listadoButton.setCheckable(False)
        self.listadoButton.setChecked(False)
        self.listadoButton.setObjectName("listadoButton")
        self.verticalLayout.addWidget(self.listadoButton)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout.addItem(spacerItem2)
        self.logoutButton = QtWidgets.QPushButton(Menu)
        self.logoutButton.setObjectName("logoutButton")
        self.verticalLayout.addWidget(self.logoutButton)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout.addItem(spacerItem3)
        self.verticalLayout_2.addLayout(self.verticalLayout)

        self.retranslateUi(Menu)
        QtCore.QMetaObject.connectSlotsByName(Menu)

    def retranslateUi(self, Menu):
        _translate = QtCore.QCoreApplication.translate
        Menu.setWindowTitle(_translate("Menu", "Menú principal"))
        self.welcomeLabel.setText(_translate("Menu", "# Bienvenido, Usuario"))
        self.recomendacionesButton.setText(_translate("Menu", "Recomendaciones basadas en mis gustos"))
        self.listadoButton.setText(_translate("Menu", "Listado Películas"))
        self.logoutButton.setText(_translate("Menu", "Cerrar Sesión"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Menu = QtWidgets.QDialog()
    ui = Ui_Menu()
    ui.setupUi(Menu)
    Menu.show()
    sys.exit(app.exec_())
